version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kokekiko2525
      MYSQL_DATABASE: anki_db
      MYSQL_USER: Alan
      MYSQL_PASSWORD: kokekiko2525
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./db/config/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - anki-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: api-server
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_USER: Alan
      DB_PASSWORD: kokekiko2525
      DB_NAME: anki_db
    networks:
      - anki-network

  client:
    build:
      context: ./fronted
      dockerfile: Dockerfile
    container_name: client-server
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - anki-network

networks:
  anki-network:
    driver: bridge
