version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kokekiko2525
      MYSQL_DATABASE: anki_db
      MYSQL_USER: Alan
      MYSQL_PASSWORD: kokekiko2525
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./db/config/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - anki-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate
    command: ["-path", "/migrations", "-database", "mysql://Alan:kokekiko2525@tcp(mysql-server:3306)/anki_db", "up"]
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - anki-network
  client:
    build:
      context: ./fronted
    container_name: client-server
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started
    networks:
      - anki-network
  api:
    build:
      context: ./api-server
    container_name: api-server
    ports:
      - "8000:8000"
    depends_on:
      migrate:
        condition: service_completed_successfully
      mysql:
        condition: service_started
    environment:
      DB_HOST: mysql-server
      DB_USER: Alan
      DB_PASSWORD: kokekiko2525
      DB_NAME: anki_db
    networks:
      - anki-network
networks:
  anki-network:
